# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  title = "Bosscha Observatory"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  copyright = "&copy; {year} Bosscha Observatory"
  office_hours = ["Monday - Friday 09:00 - 15:00 Western Indonesian Time (WIB)"]
# [en.params]
#  languageName = "EN"
 
# Uncomment the lines below to configure your website in a second language.
[id]
  languageCode = "id"
  # languageName = "ID"
  contentDir = "content/id"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
