# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "Beranda"
#   url = "/"
#   weight = 5

[[main]]
  name = "Tentang Kami"
  identifier = "about"
  url = "#about"
  weight = 10

# ------------------------------------------------
# PROFIL
# ------------------------------------------------

[[main]]
  name = "Profil dan Sejarah"
#   name = "PROFIL"
  parent = "about"
  url = "/author-detil/"
  weight = 11

[[main]]
  name = "Staf"
  parent = "about"
  url = "/author-detil/team/"
  weight = 12

# [[main]]
#   name = "Sejarah"
#   parent = "about"
#   url = "/author-detil/"
#   weight = 13

[[main]]
  name = "Instrumen"
  parent = "about"
  url = "/author-detil/instrumen/"
  weight = 13

[[main]]
  name = "Fasilitas Penunjang"
  parent = "about"
  url = "/author-detil/non-instrumen/"
  weight = 14

# ------------------------------------------------
# PENELITIAN & PENDIDIKAN
# ------------------------------------------------

[[main]]
  name = "Penelitian & Pendidikan"
#   name = "PENELITIAN & PENDIDIKAN"
  identifier = "penelitian"
  url = "/penelitian/"
  weight = 20

[[main]]
  name = "Topik"
  parent = "penelitian"
  url = "/penelitian/"
  weight = 21

[[main]]
  name = "Publikasi"
  parent = "penelitian"
  url = "/id/publication/"
  weight = 22
[[main]]
  name = "Layanan Magang"
  parent = "penelitian"
  url = "/id/akademik/"
  weight = 23

# [[main]]
#   name = "Pengamatan Matahari"
#   parent = "penelitian"
#   url = "/penelitian/matahari/"
#   weight = 24

# [[main]]
#   name = "Kolokium"
#   parent = "penelitian"
#   url = "/penelitian/kolokium/"
#   weight = 24

# [[main]]
#   name = "Akademik"
#   url = "/akademik/"
#   weight = 30

# --------------------------------------------------------------
# KUNJUNGAN
# --------------------------------------------------------------
[[main]]
  name = "Kunjungan ke Observatorium"
  identifier = "kunjungan"
  parent = "layanan"
  url = "/kunjungan/"
  weight = 30

[[main]]
  name = "Program & Jadwal"
  parent = "kunjungan"
  url = "/kunjungan/"
  weight = 31

[[main]]
  name = "Tips & Aturan Berkunjung"
  parent = "kunjungan"
  url = "/kunjungan/aturan/"
  weight = 32

[[main]]
  name = "Pendaftaran"
  parent = "kunjungan"
  url = "/kunjungan/daftar/"
  weight = 33

# [[main]]
#   name = "Jadwal"
#   parent = "kunjungan"
#   url = "/kunjungan/siang/"
#   weight = 24

# -------------------------------------------------------------
# MEDIA
# -------------------------------------------------------------
[[main]]
        # name = "MEDIA"
        name = "Media"
        identifier = "media"
        url = "#"
        weight = 40

[[main]]
  name = "Rilis Media"
  parent = "media"
  url = "/media/"
  weight = 41

[[main]]
  name = "Newsletter"
  parent = "media"
  url = "/media/newsletter/"
  weight = 42

[[main]]
  name = "Berita"
  parent = "media"
  url = "/post/"
  weight = 43

[[main]]
  name = "Kalender Astronomi"
  parent = "media"
  url = "/layanan/astrocal/"
  weight = 44



# [[main]]
#   name = "Tautan"
#   url = "#projects"
#   weight = 40

[[main]]
  name = "Galeri"
  parent = "media"
  #url = "/gallery-test3/"
  url = "/gallery/"
  weight = 45
# --------------------------------------------------------------
# ASTRO UNTUK PUBLIK
# --------------------------------------------------------------
[[main]]
#   name = "ASTRONOMI UNTUK PUBLIK"
  name = "Astronomi untuk Publik"
  identifier = "layanan"
  url = "/layanan/"
  weight = 50

# [[main]]
#   name = "Materi Edukasi Astronomi"
#   parent = "layanan"
#   identifier = "edukasi astro"
#   url = "/layanan/belajarastro/"
#   weight = 51

# [[main]]
#   name = "Belajar Astronomi Yuk"
#   parent = "edukasi astro"
#   url = "/layanan/belajarastro/"
#   weight = 41

[[main]]
  name = "Materi Edukasi Astronomi"
  parent = "layanan"
  url = "/layanan/material/"
  weight = 51

# [[main]]
#   name = "Prakarsa Langit Gelap"
#   parent = "layanan"
#   url = "/layanan/prakarsalangitgelap/"
#   weight = 52

# [[main]]
#   name = "Perpustakaan"
#   parent = "layanan"
#   url = "#"
#   weight = 45


[[main]]
  name = "Program dan Layanan Daring"
  parent = "layanan"
  url = "/layanan/"
  weight = 53

[[main]]
  name = "Kegiatan Lampau"
  parent = "layanan"
  url = "/layanan/pvlm-2020/"
  weight = 57

# [[main]]
#   name = "Pustaka Pertanyaan"
#   parent = "layanan"
#   url = "/layanan/tanya/"
#   weight = 58

# [[main]]
#   name = "Tautan"
#   parent = "layanan"
#   url = "tautan/"
#   weight = 48

# [[main]]
#     name = "Polusi Cahaya"
#     parent = "layanan"
#     url = "/layanan/langitmalam"
#     weight = 59

# [[main]]
#   name = "Tim Pendidikan & Penjangkauan Publik"
#   parent = "layanan"
#   url = "#"
#   weight = 59
# ------------------------------------------------------------------------------------
# Cuaca
# ------------------------------------------------------------------------------------
[[main]]
  name = "Cuaca"
  # parent = "layanan"
  url = "../aws/"
  weight = 56

# ------------------------------------------------------------------------------------
# KONTAK
# ------------------------------------------------------------------------------------
[[main]]
  name = "Kontak"
  url = "/kontak/"
  weight = 60

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40

# [[main]]
#   name = "Contact"
#   url = "#contact"
#   weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
