# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Beranda"
  url = "/"
  weight = 5

[[main]]
  name = "Tentang Kami"
  identifier = "about"
  url = "#about"
  weight = 10

# ------------------------------------------------
# PROFIL
# ------------------------------------------------

[[main]]
  name = "Profil"
  parent = "about"
  url = "#about"
  weight = 11

[[main]]
  name = "Staf"
  parent = "about"
  url = "#people"
  weight = 12

[[main]]
  name = "Sejarah"
  parent = "about"
  url = "/author-detil/"
  weight = 13

[[main]]
  name = "Fasilitas"
  parent = "about"
  url = "/author-detil/instrumen/"
  weight = 14

[[main]]
  name = "Berita"
  parent = "about"
  url = "/post/"
  weight = 15

# ------------------------------------------------
# PENELITIAN & PENDIDIKAN
# ------------------------------------------------

[[main]]
  name = "Penelitian & Pendidikan"
  identifier = "penelitian"
  url = "/penelitian/"
  weight = 20

[[main]]
  name = "Topik"
  parent = "penelitian"
  url = "/penelitian/"
  weight = 21

[[main]]
  name = "Publikasi"
  parent = "penelitian"
  url = "/id/publication/"
  weight = 22
[[main]]
  name = "Layanan Magang"
  parent = "penelitian"
  url = "/id/akademik/"
  weight = 23

# [[main]]
#   name = "Pengamatan Matahari"
#   parent = "penelitian"
#   url = "/penelitian/matahari/"
#   weight = 24

# [[main]]
#   name = "Kolokium"
#   parent = "penelitian"
#   url = "/penelitian/kolokium/"
#   weight = 24

# [[main]]
#   name = "Akademik"
#   url = "/akademik/"
#   weight = 30

# --------------------------------------------------------------
# KUNJUNGAN
# --------------------------------------------------------------
[[main]]
  name = "Kunjungan"
  identifier = "kunjungan"
  url = "/kunjungan/"
  weight = 30

[[main]]
  name = "Program & Jadwal"
  parent = "kunjungan"
  url = "/kunjungan/"
  weight = 31

[[main]]
  name = "Tips & Aturan Berkunjung"
  parent = "kunjungan"
  url = "/kunjungan/aturan/"
  weight = 32

[[main]]
  name = "Pendaftaran"
  parent = "kunjungan"
  url = "/kunjungan/daftar/"
  weight = 33

# [[main]]
#   name = "Jadwal"
#   parent = "kunjungan"
#   url = "/kunjungan/siang/"
#   weight = 24


# --------------------------------------------------------------
# LAYANAN PUBLIK
# --------------------------------------------------------------
[[main]]
  name = "Layanan"
  identifier = "layanan"
  url = "/layanan/"
  weight = 40

[[main]]
  name = "Material dan Modul"
  parent = "layanan"
  url = "/layanan/material/"
  weight = 41

[[main]]
  name = "Kalender Astronomi"
  parent = "layanan"
  url = "/layanan/astrocal/"
  weight = 42

[[main]]
  name = "Press-release"
  parent = "layanan"
  url = "/layanan/pressrelease"
  weight = 43

# [[main]]
#   name = "Tautan"
#   url = "#projects"
#   weight = 40

[[main]]
  name = "Galeri"
  parent = "layanan"
  # url = "/gallery-test3/"
  url = "/gallery-test2/"
  weight = 44

# [[main]]
#   name = "Perpustakaan"
#   parent = "layanan"
#   url = "#"
#   weight = 45

[[main]]
  name = "Kondisi Cuaca"
  parent = "layanan"
  url = "../aws/"
  weight = 46

[[main]]
  name = "Program dan Layanan Daring"
  parent = "layanan"
  url = "/layanan/kelasastro"
  weight = 47

 [[main]]
  name = "Tautan"
  parent = "layanan"
  url = "tautan/"
  weight = 48

# ------------------------------------------------------------------------------------
# KONTAK
# ------------------------------------------------------------------------------------
[[main]]
  name = "Kontak"
  url = "/kontak/"
  weight = 50

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40

# [[main]]
#   name = "Contact"
#   url = "#contact"
#   weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
